config/routes.rb
Treebook::Application.routes.draw do
  get 'profiles/show'

  devise_for :users

devise_scope :user do
    get 'registration', to: 'devise/registrations#new', as: :register
    get 'signin', to: 'devise/sessions#new', as: :signin
    get 'signout', to: 'devise/sessions#destroy', as: :signout
end

  resources :users
  resources :statuses
  root to: "statuses#index"

  get '/:id', to: 'profiles#show', as: :user_profile

end

app/models/status.rb
class Status < ActiveRecord::Base
	#attr_accessible :content, :user_id
	belongs_to :user
	validates :content, presence: true,
						length: { minimum: 2 }
	validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # attr_accessible :first_name, :last_name, :profile_name, :email, :password, :password_confirmation, :remember_me
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :statuses

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :profile_name, presence: true,
                           uniqueness: true,
                           format: {
                            with: /[a-zA-Z0-9_-]+/,
                            message: 'should be in the right format.'
                           }


  def full_name
   	first_name + " " + last_name
  end

  def gravatar_url
    stripped_email = email.strip
    downcased_email = stripped_email.downcase
    hash = Digest::MD5.hexdigest(downcased_email)
    "http://gravatar.com/avatar/#{hash}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  	protected
  	def configure_permitted_parameters
  		devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:first_name, :last_name, :profile_name, :email, :password, :password_confirmation) }
 		devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :profile_name, :email, :password, :password_confirmation) }
 	end

end

  

  

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
  	@user = User.find_by_profile_name(params[:id])
  	if @user
  		@statuses = @user.statuses.all
  		render action: :show
	else
	  	render file: 'public/404', status: 404, formats: [:html]
  	end
  end
end

app/controllers/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController

end		

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  def profile_get
    @profile = Status.user.profile_name 
  end
  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render action: 'show', status: :created, location: @status }
      else
        format.html { render action: 'new' }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:name, :content, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def  flash_class(type)
		case type
		when "alert"
			"bg-warning"
		when "notice"
			"bg-success"
		else
			""
		end
	end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Treebook</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-default navbar-fixed-top">
 <div class="container">
 	<div class="navbar-header">
 		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
 			<span class="sr-only">Toggle navigation</span>
 			<span class="icon-bar"></span>
 			<span class="icon-bar"></span>
 			<span class="icon-bar"></span>
 		</button>
 		<%= link_to "Treebook", "/", :class => "navbar-brand" %>
 	</div>
 	<div class="navbar-collapse collapse">
 	 	<ul class="nav navbar-nav">
 			<li></li>
 		</ul>
 		<ul class="nav navbar-nav pull-right">
 		<% if user_signed_in? %>
 			<li class="btn-ready"><%= link_to current_user.full_name, "#" %></li>
 			<li class="btn-ready"><%= link_to "Sign out", signout_path %>
 			</li>
 		<% else %>
 			<li class="btn-ready"><%= link_to "Sign up", register_path %></li>
 			<li class="btn-ready"><%= link_to "Sign in", signin_path %></li>
 		<% end %>
 		</ul>
 	</div>
 </div>
 	
</div>
	<div class="container">
		<div class="notice">
		<p style="padding-top: 40px"></p>
		<% flash.each do |type, message| %>
			<button type="button" class="close" data-dismiss="alert">&times;</button>
			<div class="<%= flash_class type %>" style="height: 50px; line-height: 50px;">&nbsp; &nbsp; &nbsp; <%= message %></div>
		<% end %>
		</div>
<%= yield %>
	</div>


</body>
</html>

app/views/profiles/show.html.erb
<h1><%= @user.full_name %></h1>

<% if @statuses %>
	<% @statuses.each do |status| %>
	
  <div class="status">
  	<div class="row">
	  	<div class="col-md-1"><%= image_tag status.user.gravatar_url %></div>
	  	<div class="col-md-8">
		    <p><%= status.content %></p>
		    <span class="meta"><%= link_to time_ago_in_words(status.created_at) + " ago", status %></span>
		    <div class="admin">|  <span><%= link_to "Edit", edit_status_path(status) %></span> | <span><%= link_to "Delete", status , method: :delete , data: { confirm: "Are you sure?"} %></span>
		    </div>
	  	</div>
	  </div>
  </div>
	<% end %>
<% end %>

app/views/statuses/_form.html.erb
<%= simple_form_for(@status, html: {class: "form-horizontal"}) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.input :user_id , collection: User.all, label_method: :full_name %>
    <%= f.input :content %>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<div class="page-header">
    <h1>All Statuses</h1>
</div>

<%= link_to "New status", new_status_path, class: "btn btn-primary" %>

<% @statuses.each do |status| %>
  <div class="status">
  	<div class="row">
	  	<div class="col-md-1"><%= image_tag status.user.gravatar_url %></div>
	  	<div class="col-md-8">
		  	<span><%= link_to status.user.full_name, user_profile_path(status.user.profile_name) %></span>
		    <p><%= status.content %></p>
		    <span class="meta"><%= link_to time_ago_in_words(status.created_at) + " ago", status %></span>
		    <div class="admin">|  <span><%= link_to "Edit", edit_status_path(status) %></span> | <span><%= link_to "Delete", status , method: :delete , data: { confirm: "Are you sure?"} %></span>
		    </div>
	  	</div>
	  </div>
  </div>
<% end %>
<br />
<br />
<%= link_to "Sign Up", new_user_registration_path, :class => "btn btn-primary sign_out" %>
<%= link_to "Sign In", new_user_session_path, :class => "btn btn-primary sign_out" %>
<%= link_to "Sign out", destroy_user_session_path, :method => :delete, :class => "btn btn-primary sign_out" %>

app/views/statuses/new.html.erb
<h1>New status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<div class="page-header">
  <h1></h1>
</div>
<p><%= @status.user.full_name %></p>
<p><%= @status.content %></p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>